### ISSUE TITLE
Not working on Mac

### ISSUE THREAD

**Issue by JFtechOfficial** [jarbun/downline#12]
Hi, I have installed Downline 1.3.1 on MacOS Mojave 10.14.5. The app starts but
1) I cannot use cmd+v to paste URLs in the text-box
2) for any youtube link I insert, Downline remains in the "loading" status

Previous to this app I already had youtube-dl installed (via pip). The app also keeps loading while checking for youtube-dl updates (anyways youtube-dl CLI is updated at 2019.6.27 release and it's working correctly from terminal)

<img width="460" alt="Schermata 2019-06-30 alle 18 57 14" src="https://user-images.githubusercontent.com/36900161/60399694-e311a800-9b68-11e9-8e53-37785cb3c1af.png">

<img width="461" alt="Schermata 2019-06-30 alle 18 57 33" src="https://user-images.githubusercontent.com/36900161/60399695-ec027980-9b68-11e9-806c-2a9fdab840d4.png">

**Comment by balkarjun** [comment]
Apologies for the late reply. Unfortunately, I do not have a MacOS system to work on this issue. 

The issue with Downline remaining in the *loading* status can probably be fixed by updating youtube-dl. 
If the inbuilt updater does not work, you'll have to manually update the youtube-dl file that Downline uses. From the extracted macOS package, go to **Contents -> Resources -> youtube-dl** and replace the file with an updated version of youtube-dl.

**Comment by ofrades** [comment]
same problem here

**Comment by snte** [comment]
I was able to fix it manually:

- Locate Downline app
- Right click app and select **Show Package Contents**
- For me **ffmpeg** and **youtube-dl** folders were located in **Contents -> resources-1**, so i moved both folders to **Contents -> Resources**

Maybe this is enough to make it work. I also made sure that the binaries  **ffmpeg** and **youtube-dl** are executable, with chmod on terminal:

`sudo chmod a+rx /Applications/Downline.app/Contents/Resources/ffmpeg/ffmpeg`
`sudo chmod a+rx /Applications/Downline.app/Contents/Resources/youtube-dl/youtube-dl`

Did work for me. Thanks for the useful app!

**Comment by JFtechOfficial** [comment]
thank you, this solved the download problem!

**Comment by colineberly** [comment]
Having this same issue. Fix above doesn't work for me.
